sudo: required

services:
  - docker

language: go

env:
  - DOCKER_API_VERSION=1.24

go:
  - 1.7.4

before_install:
  - ci/install-glide
  - ci/install-golint

script:
  - make lint vet licensecheck test bin
  - ci/setup-docker-network
  - make integration

cache:
  directories:
    - $HOME/.glide/cache
